# Generated by Django 5.2.1 on 2025-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reservas', models.IntegerField()),
                ('media_valor_reservas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_clientes', models.IntegerField()),
                ('media_idade_clientes', models.IntegerField()),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
