# Generated by Django 5.2.1 on 2025-10-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacotes_vendidos', models.IntegerField(default=0, verbose_name='Quantidade de Pacotes Vendidos')),
                ('idade_media_clientes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Idade Média dos Clientes')),
                ('valor_medio_pacotes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Médio dos Pacotes')),
                ('valor_minimo_pacote', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mínimo do Pacote')),
                ('valor_maximo_pacote', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Máximo do Pacote')),
                ('data_analise', models.DateTimeField(auto_now_add=True, verbose_name='Data da Análise')),
            ],
            options={
                'verbose_name': 'Análise de Dados',
                'verbose_name_plural': 'Análises de Dados',
                'unique_together': {('id',)},
            },
        ),
    ]
