# Generated by Django 5.0.6 on 2024-06-03 14:00
from django.db import migrations

def popular_analise_dados(apps, schema_editor):
    AnaliseDados = apps.get_model('analise', 'AnaliseDados')
    

    dados_mocados = {
        'pacotes_vendidos': 150,
        'idade_media_clientes': 35.75,
        'valor_medio_pacotes': 1250.50,
        'valor_minimo_pacote': 499.90,
        'valor_maximo_pacote': 3500.00,
    }


    AnaliseDados.objects.update_or_create(
        id=1, 
        defaults=dados_mocados
    )

def reverter_popular_analise_dados(apps, schema_editor):
    AnaliseDados = apps.get_model('analise', 'AnaliseDados')

    AnaliseDados.objects.filter(id=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_analise_dados, reverter_popular_analise_dados),
    ]
