# Generated by Django 5.2.1 on 2025-05-17 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numero_reserva', models.CharField(default='0b97c7db6c', max_length=10, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('colaborador_responsavel', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_ida', models.DateField()),
                ('data_volta', models.DateField()),
                ('comentarios_adicionais', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='parceiros.parceiro')),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clientes.cliente')),
            ],
        ),
    ]
