# Generated by Django 5.2 on 2025-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='599212f312', max_length=10, primary_key=True, serialize=False),
        ),
    ]
