# Generated by Django 5.2 on 2025-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='c731bfdcc2', max_length=10, primary_key=True, serialize=False),
        ),
    ]
