# Generated by Django 5.2.1 on 2025-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='b8879b43fb', max_length=10, primary_key=True, serialize=False),
        ),
    ]
