# Generated by Django 5.2.1 on 2025-11-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='d628571241', max_length=10, primary_key=True, serialize=False),
        ),
    ]
