# Generated by Django 5.2.1 on 2026-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_novos_campos_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='520124d181', max_length=10, primary_key=True, serialize=False),
        ),
    ]
