# Generated by Django 5.2.1 on 2026-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='9c5e5a3b7c', max_length=10, primary_key=True, serialize=False),
        ),
    ]
