# Generated by Django 5.2.1 on 2026-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='c00dbd6fc7', max_length=10, primary_key=True, serialize=False),
        ),
    ]
